property_search_task:
  description: >
    Analyze the user query: "{query}" and extract key information about the property search request:
    - Buy, rent, or sold?
    - Desired location
    - Property type
    - Price range
    - Bedrooms, bathrooms, features

    Use the realtor tools to search for properties that match the criteria.
    For each property found, gather:
    - Address
    - Latitude and Longitude
    - Price, bedrooms, bathrooms
    - Photos (if available)
    - Agent info
    - Environmental risk data
    - Market trends

    For the most promising or urban-located properties, call the "get_walkscore" tool
    using the correct address, latitude, and longitude format.

    Include Walk Score, Transit Score, and Bike Score in your final results for those properties.

  expected_output: >
    A well-structured list of property listings, each with rich metadata.
    For selected listings, include a formatted section summarizing Walk Score data.
  agent: property_search
  output_file: output/property_list_with_walkscore.json

render_report:
  description: >
    Analyze the enhanced property list and create a final report with summaries and insights.
    Your report should:
    1. Begin with an executive summary
    2. Include all key data from the listings
    3. Highlight any patterns or market insights
    4. Recommend top properties based on user preferences
    5. Be formatted cleanly for readability
  expected_output: >
    A markdown or PDF report summarizing the top real estate findings and mobility scores.
  agent: property_search
  context:
    - property_search_task