property_search_task:
  description: >
    Analyze the user query: "{query}" and extract key information about the property search request:
    - Buy, rent, or sold?
    - Desired location
    - Property type
    - Price range
    - Bedrooms, bathrooms, features

    Then, use the appropriate tools to search for properties that match these criteria.

    ## Tool instructions
    - You can combine multiple tools if needed, using the output of one tool as input to another.
    - Many of the search tools have pagination, so you may need to use multiple tools to get a complete list of properties.
    - Do not overwhelm the user with too many properties.
    - Not all tools are necessary, use only the tools that are relevant to the search criteria.

    If the query is ambiguous, ask the user for clarification.
  expected_output: >
    A well-structured list of property listings, each with rich metadata.
  agent: property_search

lifestyle_filter_task:
  description: >
    If the user's query includes lifestyle preferences (e.g., gym, nightlife, restaurants), use the get_nearby_places tool to find those amenities around each property.
    Use the tool to find only the types of amenities the user asked for.
    This helps prioritize or annotate listings with nearby lifestyle conveniences.
  expected_output: >
    A mapping of properties to their surrounding lifestyle amenities.
  agent: lifestyle_filter
  context:
    - property_search_task


render_report:
  description: >
    Analyze the property list and create json object with property list
  expected_output: >
    A JSON object containing the property list with the following structure:
    {
      "properties": [
        {
          "address": "123 Main St",
          "price": 100000,
          "bedrooms": 3,
          "bathrooms": 2,
          "sqft": 1500,
          "agent": "John Doe",
          "agent_phone": "555-1234",
          "agent_email": "john.doe@example.com",
          "environmental_risk": "low",
          "photos": [
            "https://example.com/photo1.jpg",
            "https://example.com/photo2.jpg",
            "https://example.com/photo3.jpg"
          ]
        }
      ]
    }

  agent: output_agent
  output_file: output/property_list.json
  context:
    - property_search_task
    - lifestyle_filter_task

summarize_properties_task:
  description: >
    Write a short 3–5 line markdown summary based only on what the user was looking for and what the data showed.
    Skip generic observations.
    Mention lifestyle factors like gyms, transit, or walkability *only if the user asked for them* and data supports it.
    Keep it casual, honest, direct and clear — like you’re giving a quick recommendation.
  expected_output: >
    A markdown summary that is simple, specific, and free of generic AI tone.
    Avoid listing every property. Focus on user interests and what’s actually notable.
  agent: summarizer
  output_file: output/property_summary.md
  context:
    - property_search_task
    - lifestyle_filter_task
